#!/bin/bash
#
# Returns remaining duration of current track

tpos=$(osascript -e 'tell app "Spotify" to player position')
tdur=$(osascript -e 'tell app "Spotify" to duration of current track')
echo $tdur-$tpos | bc | sed -e 's/\(\.[0-9]\)[0-9]*/\1/g'