#!/bin/sh
#
# Sets Spotify's volume.
#
# $1 - The new volume setting.

osascript << APPLESCRIPT
if application "Spotify" is running then
  tell application "Spotify" to set sound volume to $1
end if
APPLESCRIPT